# Generated by Django 3.1.1 on 2020-09-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='phonenumber',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
